name: Build and Deploy Code

on: 
  push:
    branches: 
      - "main"
      - "develop"
    
  pull_request:
    branch:
      - "main"
      - "develop"

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi
        uses: echo "hello world"
